["Spawning Settings"]
	#Spawn Radius: How far away from the player (in blocks) dust will attempt to spawn.
	#Keep this lower than Hard Cap.
	# Default: 10
	# Range: 1 ~ 32
	ambientRadius = 10
	#Hard Cap Radius: The absolute max distance dust can exist.
	#Particles further than this are deleted instantly.
	#MUST be larger than ambientRadius (recommended +2 or +3 blocks).
	# Default: 12
	# Range: 1 ~ 48
	ambientHardCapRadius = 12
	#Max dust particles allowed per single block.
	# Default: 14
	# Range: 1 ~ 20
	ambientBlockCap = 14
	#Minimum block light level required for ambient dust to spawn.
	# Default: 6
	# Range: 0 ~ 15
	minBlockLight = 6
	#Daytime Light Threshold: The minimum difference between Block Light and Sky Light required for dust to spawn during the day.
	#Increase this to prevent dust spawning in sun-lit houses.
	#Formula: (BlockLight - SkyLight) > Threshold
	# Default: 5
	# Range: 0 ~ 15
	daytimeLightDiff = 5

["Visual Settings"]
	#Base opacity for ambient dust (0.22 for vanilla, 0.45+ for shaders)
	# Default: 0.22
	# Range: 0.0 ~ 1.0
	ambientDustOpacity = 0.22
	#Base size of the dust particles.
	# Default: 0.44
	# Range: 0.01 ~ 1.0
	particleSize = 0.44
	#Base lifetime of the dust particles in ticks.
	# Default: 200
	# Range: 20 ~ 1000
	particleLifetime = 200

["Color and Tinting"]
	#How strongly colored lights (like soul fire) tint the dust. 0.0 = no tint, 1.0 = full color
	# Default: 0.6
	# Range: 0.0 ~ 1.0
	tintStrength = 0.6
	#List of blocks and their hex colors for dust tinting.
	#Format: 'modid:block_name=#RRGGBB'
	#Example 1: 'minecraft:torch=#FFDB8A'
	#Example 2: 'mymod:custom_lantern=#00FF00'
	#Note: The block must actually emit light for the tint to apply. Make sure to include the '#' before the hex code!
	customTints = ["minecraft:torch=#FFDB8A", "minecraft:lantern=#FFDB8A", "minecraft:soul_torch=#4CBAFF", "minecraft:soul_lantern=#4CBAFF", "minecraft:soul_campfire=#4CBAFF", "minecraft:redstone_torch=#FF4C4C", "minecraft:redstone_lamp=#FF4C4C", "minecraft:amethyst_cluster=#CC66FF", "minecraft:glowstone=#FFD670", "minecraft:shroomlight=#FF9933"]

["Interaction and Physics"]
	#Radius squared for player interaction (slashing/moving).
	# Default: 4.0
	# Range: 0.0 ~ 16.0
	playerInteractRadius = 4.0
	#Number of dust particles spawned when a block is broken
	# Default: 12
	# Range: 0 ~ 50
	breakParticleCount = 12
	#How fast the dust shoots out from a broken block
	# Default: 0.1
	# Range: 0.0 ~ 1.0
	breakParticleSpeed = 0.1
