name = "/c/AKE und PANZER - Server"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76392cbbf77a5f903cfd88f7acc77d97fcf4a07d62dd3398a1b3432313456b4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
