name = "/c/AKE und PANZER - Server"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "720ebb7f983e4a0277d1f59e88729986198fff5de73b9fb5a60b82958f0739e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
