name = "/c/AKE und PANZER - Server"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "012c0597a4ac4e3c7af9d4ecd573ffd8c692b628b9dffaa97855b98e77200b43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
