name = "/c/AKE und PANZER - Basic"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae5f303049f2f23a14113f442f74bb6eceae692a7a1abdde449e1bd92c37965e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
