name = "/c/AKE und PANZER - Basic"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b5172ac1b4a8a0bd4cc75712689f177f426b0e35555b7b63fa851b68194463a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
