name = "/c/AKE und PANZER - Basic"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abf7d2248a7d1d5d19ac1d1d1be6437419453906c51efb8e076783adddc6f6bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
