name = "/c/AKE und PANZER"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7297d5094edf6e411e287710fa26eb37c3dbf3e5128f39b2a8804c1e50d8f02f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
