name = "/c/AKE und PANZER"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe98ebbbdd1c7ed24aef0189311805998536be461276a89fbd9f0c7d3912f11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
