name = "/c/AKE und PANZER"
author = "Kretinum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d48a732b5791ca9ca5f64cf7858d70676786c47439cd22647862ad09292d326"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
